macro(nose_tests_init)
    find_package(PythonInterp)
    if(NOT PYTHONINTERP_FOUND)
        MESSAGE(WARNING "Python required to run tests")
    else(NOT PYTHONINTERP_FOUND)
        find_package(PyNose)
        if(NOT PYNOSE_FOUND)
            MESSAGE(WARNING "Python nose required to run tests")
        else(NOT PYNOSE_FOUND)
            add_custom_target(tests COMMENT "Run all tests target")
        endif(NOT PYNOSE_FOUND)
    endif(NOT PYTHONINTERP_FOUND)
endmacro(nose_tests_init)
macro(nose_add_test_dir tname tdir)
    if(PYNOSE_FOUND)
        add_custom_target(${tname} 
            COMMAND ${PYNOSE_EXECUTABLE} ${tdir} COMMENT "Tests for ${tname}")
        add_dependencies(tests ${tname})
    endif(PYNOSE_FOUND)
endmacro(nose_add_test_dir tdir tname)
