# Locate pod2man
# This module defines
#  POD2MAN_FOUND
#  POD2MANE_EXECUTABLE - path to pod2man

find_program(POD2MAN_EXECUTABLE NAMES pod2man)
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Pod2man DEFAULT_MSG POD2MAN_EXECUTABLE)
MARK_AS_ADVANCED(POD2MAN_EXECUTABLE)
